#cloud-config

write_files:
  - path: "/etc/cargo/nginx.conf"
    content: |
      server {
          server_name _;

          location / {
              add_header Content-Type text/plain;

              return 200 'cargo is runing on $hostname at $date_gmt';
          }
      }

coreos:
  update:
    reboot-strategy: off

  units:
    - name: nginx.service
      command: start
      content: |
        [Unit]
        Description=Nginx
        After=docker.service
        Requires=docker.service
        [Service]
        TimeoutStartSec=0
        ExecStartPre=-/usr/bin/docker kill nginx
        ExecStartPre=-/usr/bin/docker rm nginx
        ExecStartPre=/usr/bin/docker pull nginx
        ExecStart=/usr/bin/docker run --name nginx -p 80:80 -v /etc/cargo/nginx.conf:/etc/nginx/conf.d/default.conf nginx
        ExecStop=/usr/bin/docker stop nginx
        User=core
        Restart=always
